version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_agent_ia
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agent_ia
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis_agent_ia
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
      --maxmemory-policy noeviction
    restart: unless-stopped